### ISSUE TITLE
Why do I get "Avoid referencing unbound methods which may cause unintentional scoping of `this`. eslint@typescript-eslint/unbound-method" in this case?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/eslint-plugin-svelte3#102]
I'm using Svelte 3, Typescript and this code:

- loginStore.ts:

```ts
import { writable } from "svelte/store";

const store = () => {
  const state = {
    isLoggedIn: false,
  };

  const { subscribe, update } = writable(state); // warning: Avoid referencing unbound methods which may cause unintentional scoping of `this`. eslint@typescript-eslint/unbound-method (2 times)

  const methods = {
    OnInit() {
      this.Login(); // warning: Unsafe member access .Login on an any value. eslint@typescript-eslint/no-unsafe-member-access and another warning: Unsafe call of an any typed value. eslint@typescript-eslint/no-unsafe-call
    },

    Login() {
      if (window.localStorage.isLoggedIn) {
        update(() => {
          state.isLoggedIn = true;
          return state;
        });
      }
    },

    async Logout() {
      await doLogout();
      update(() => {
        state.isLoggedIn = false;
        return state;
      });
    },
  };

  return {
    subscribe,
    ...methods,
  };
};

export default store();
```

But `@typescript-eslint` is giving me these errors:

1. `Avoid referencing unbound methods which may cause unintentional scoping of this` 2 times on line:

    ```ts
    const { subscribe, update } = writable(state)
    ```

1. `Unsafe member access .Login on an any value` on line:

    ```ts
    this.Login()
    ```

1. `Unsafe call of an any typed value` on line:

    ```ts
    this.Login()
    ```

How can I fix these warnings?

**Comment by JounQin** [comment]
There is nothing related to this plugin...

And it's expected AFAIK.

For the first one, `writable` is a plain function without `this` used inside, so if you want, we should change the source svelte code from `export function writable()` to `export const writable = ()` or `export function writable (this: never)`.

For the other warnings, can just add

```js
OnInit(this: typeof methods)
```

**Comment by frederikhors** [comment]
> we should change the source svelte code from `export function writable()` to `export const writable = ()` or `export function writable (this: never)`

Do you mean we should change Svelte 3 types?

**Comment by frederikhors** [comment]
> ```js
> OnInit(this: typeof methods)
> ```

It doesn't fix the warning.

**Comment by JounQin** [comment]
> > ```js
> > OnInit(this: typeof methods)
> > ```
> 
> It doesn't fix the warning.
> 
> Can you please elaborate on this?

Sorry about that, actually I don't have the problem.

https://typescript-eslint-armano.netlify.app/repl/#sourceType=module&rules=JTdCJTIyJTQwdHlwZXNjcmlwdC1lc2xpbnQlMkZuby11bnNhZmUtbWVtYmVyLWFjY2VzcyUyMiUzQSU1QiUyMmVycm9yJTIyJTVEJTdE&code=JTIyY29uc3QlMjBtZXRob2RzJTIwJTNEJTIwJTdCJTVDbiUyMCUyMCUyMCUyME9uSW5pdCgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHRoaXMuTG9naW4oKSUzQiUyMCUyRiUyRiUyMHdhcm5pbmclM0ElMjBVbnNhZmUlMjBtZW1iZXIlMjBhY2Nlc3MlMjAuTG9naW4lMjBvbiUyMGFuJTIwYW55JTIwdmFsdWUuJTIwZXNsaW50JTQwdHlwZXNjcmlwdC1lc2xpbnQlMkZuby11bnNhZmUtbWVtYmVyLWFjY2VzcyUyMGFuZCUyMGFub3RoZXIlMjB3YXJuaW5nJTNBJTIwVW5zYWZlJTIwY2FsbCUyMG9mJTIwYW4lMjBhbnklMjB0eXBlZCUyMHZhbHVlLiUyMGVzbGludCU0MHR5cGVzY3JpcHQtZXNsaW50JTJGbm8tdW5zYWZlLWNhbGwlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTVDbiU1Q24lMjAlMjAlMjAlMjBMb2dpbigpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyRiUyRiU1Q24lMjAlMjAlMjAlMjAlN0QlMkMlNUNuJTVDbiUyMCUyMCUyMCUyMGFzeW5jJTIwTG9nb3V0KCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTJGJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lN0QlM0IlNUNuJTIy

**Comment by JounQin** [comment]
> > we should change the source svelte code from `export function writable()` to `export const writable = ()` or `export function writable (this: never)`
> 
> Do you mean we should change Svelte 3 types?

Yes.

**Comment by frederikhors** [comment]
> > > ```js
> > > OnInit(this: typeof methods)
> > > ```
> > 
> > 
> > It doesn't fix the warning.
> > Can you please elaborate on this?
> 
> Sorry about that, actually I don't have the problem.
> 
> playground

I cannot see your code there:

![image](https://user-images.githubusercontent.com/41120635/111554527-d68f1200-8786-11eb-9f66-0d21769a57ee.png)

**Comment by JounQin** [comment]
What's code do you want, the playground is simplified to show what the root cause.

And which version of `typescript` and `@typescript-eslint/eslint-pluin` are you using.

**Comment by frederikhors** [comment]
I changed the [PLAYGROUND](https://typescript-eslint-armano.netlify.app/repl/#sourceType=module&rules=JTdCJTIyJTQwdHlwZXNjcmlwdC1lc2xpbnQlMkZuby11bnNhZmUtY2FsbCUyMiUzQSU1QiUyMmVycm9yJTIyJTVEJTJDJTIyJTQwdHlwZXNjcmlwdC1lc2xpbnQlMkZuby11bnNhZmUtbWVtYmVyLWFjY2VzcyUyMiUzQSU1QiUyMmVycm9yJTIyJTVEJTdE), as you can see here `this` is `any`.

![image](https://user-images.githubusercontent.com/41120635/111555236-3c2fce00-8788-11eb-9ed5-79f93524025c.png)

**Comment by frederikhors** [comment]
I'm using:

```json
"@typescript-eslint/eslint-plugin": "4.17.0",
"@typescript-eslint/parser": "4.17.0",
"typescript": "4.2.3",
```

**Comment by frederikhors** [comment]
With this `tsconfig.json`:

```json
{
  "extends": "@tsconfig/svelte/tsconfig.json",

  "compilerOptions": {
    "module": "ES2020",
    "target": "ES2020",
    "types": ["svelte", "node"]
  },

  "include": ["src/**/*", "types"],
  "exclude": ["node_modules/*", "__sapper__/*", "public/*"]
}
```

**Comment by frederikhors** [comment]
And `.eslintrc.js`:

```js
module.exports = {
  root: true,
  overrides: [
    {
      files: ['./*.js', './.*.js'],
      env: { node: true },
      parserOptions: { sourceType: 'module', ecmaVersion: 2020 },
      extends: ['eslint:recommended']
    },

    {
      files: ['*.svelte'],
      processor: 'svelte3/svelte3',
      env: { es6: true, browser: true },
      parser: '@typescript-eslint/parser',
      parserOptions: {
        tsconfigRootDir: __dirname,
        project: './tsconfig.json',
        extraFileExtensions: ['.svelte']
      },
      extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking'
      ],
      plugins: ['svelte3', '@typescript-eslint'],
      settings: { 'svelte3/typescript': require('typescript') },
      rules: {
        '@typescript-eslint/no-unsafe-member-access': 0
      }
    },

    {
      files: ['*.ts', '*.tsx'],
      env: { es6: true, browser: true },
      parser: '@typescript-eslint/parser',
      parserOptions: {
        tsconfigRootDir: __dirname,
        project: './tsconfig.json',
        extraFileExtensions: ['.svelte']
      },
      extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:@typescript-eslint/recommended-requiring-type-checking'
      ],
      plugins: ['svelte3', '@typescript-eslint'],
      settings: { 'svelte3/typescript': require('typescript') }
    }
  ]
}
```

**Comment by JounQin** [comment]
Maybe it's time to provide a runnable reproduction now.

**Comment by frederikhors** [comment]
It works now on my Playground. But I still have that problem locally. What's the typescript version of the playground?

**Comment by JounQin** [comment]
https://github.com/armano2/typescript-eslint/blob/docs-page/package.json#L126

**Comment by frederikhors** [comment]
Ok. I have the reproducible repo: https://github.com/frederikhors/issueWithThisAny

![image](https://user-images.githubusercontent.com/41120635/111556567-338cc700-878b-11eb-834b-19e51a9cc436.png)

**Comment by JounQin** [comment]
@frederikhors 

If you enabled `"noImplicitThis": true` compileOption, it will just work.

Anyway, it's a ts usage problem, not related to `eslint-plugin-svelte3` at all.

**Comment by frederikhors** [comment]
Should we add `"noImplicitThis": true` to https://github.com/sveltejs/template/blob/master/scripts/setupTypeScript.js? What do you think?

**Comment by dummdidumm** [comment]
No, that's up to the user to decide how strict he wants his type checking.

**Comment by frederikhors** [comment]
I can close this. **You people are wonderful people!**
