### ISSUE TITLE
Why cannot Typescript detect this Svelte 3 store's correct content type telling me instead it is of any type?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/eslint-plugin-svelte3#104]
Using this code and [eslint-plugin-svelte3](https://github.com/sveltejs/eslint-plugin-svelte3):

```svelte
<script lang="ts">
	import { writable } from "svelte/store";

	type Player = {
		name: string;
	};

	const playersStore = writable([] as Player[]);

	$: players = $playersStore;
</script>

{players}
```

I get this Typescript error:

`Unsafe assignment of an any value. eslint@typescript-eslint/no-unsafe-assignment`

on line:

```ts
$: players = $playersStore;
```

**Why?**

The error disappears if I use:

```ts
$: players = playersStore;
```

but I think this is not a solution: is an error, right?

**Comment by dummdidumm** [comment]
This is a known limitation cited in the readme. For now I suggest to disable these kind of rules for Svelte files.

**Comment by frederikhors** [comment]
@dummdidumm I asked it here because it's not the same as the one explained in the README.md.
