### ISSUE TITLE
Broken link in OTHER_PLUGINS.md

### ISSUE THREAD

**Issue by dvopalecky** [sveltejs/eslint-plugin-svelte3#111]
In `OTHER_PLUGINS.md` there seems to be a broken link for the eslint overrides doc
https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files (the html anchor part).

I suggest changing the link to
https://eslint.org/docs/user-guide/configuring/configuration-files#how-do-overrides-work

Thanks

**Comment by atompkins** [comment]
I just came across this. I think
[https://eslint.org/docs/user-guide/configuring/rules#using-configuration-files-1](https://eslint.org/docs/user-guide/configuring/rules#using-configuration-files-1)
is simpler.
