### ISSUE TITLE
Mixing svelte and ts file together in a project

### ISSUE THREAD

**Issue by agorer** [sveltejs/eslint-plugin-svelte3#116]
Hello,
   when working on a project that uses the recommended configuration for `typescript-eslint` and `eslint-plugin-svelte`, svelte files seem like they are not parsed properly (always returning `Unexpected token  ParseError` at the first hint of typescript).

.eslintrc:
```
{
  "plugins": ["svelte3", "@typescript-eslint"],
  "settings": {
    "svelte3/typescript": true
  },
  "parser": "@typescript-eslint/parser",
  "extends": [
    "prettier",
    "plugin:@typescript-eslint/recommended",
  ],
  "overrides": [{
    "files": ["*.svelte"],
    "processor": "svelte3/svelte3"
  }],
  "rules": {
    // Modify specific rules here
    "quotes": ["error", "single"],
  }
}
```

Example file:
```
<script lang="ts">
  let anything: string = 'hola'

  function prueba(something) {}
</script>
```

Relevant package versions:
```
    "@typescript-eslint/eslint-plugin": "^4.26.0",
    "@typescript-eslint/parser": "^4.26.0",
    "eslint": "^7.28.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "tslib": "^2.0.0",
    "typescript": "^4.2.3"
```

The specific problems seems to be with adding the `typescript-eslint` recommended configuration. If I remove `"plugin:@typescript-eslint/recommended"` from the extends config, the error disappears.

Is it a problem to extend configurations when using `eslint-plugin-svelte`?

**Comment by vgpechenkin** [comment]
Hi.
I recently set up eslint config based on this repository https://github.com/NicoCevallos/svelte-template. Maybe it helps you.

**Comment by agorer** [comment]
> Hi.
> I recently set up eslint config based on this repository https://github.com/NicoCevallos/svelte-template. Maybe it helps you.

Given that configuration is different for different types of files in that repo, aren't you using a different set of rules for svelte and ts files that way?

**Comment by vgpechenkin** [comment]
No, rules work with ts and svelte files. And you can turn off some of the rules that work incorrectly. This is my overrides (project usees  react and svelte)

```
 "overrides": [
        {
            "files": ["*.svelte"],
            "processor": "svelte3/svelte3",
            "extends": [
                "eslint:recommended",
                "plugin:@typescript-eslint/recommended",
                "plugin:@typescript-eslint/recommended-requiring-type-checking"
            ],
            "rules": {
                "@typescript-eslint/no-inferrable-types": 0,
                "@typescript-eslint/no-unsafe-member-access": 0
            }
        },
        {
            "files": ["*.ts", "*.json", "*.tsx"],
            "extends": [
                "plugin:react/recommended", // Uses the recommended rules from @eslint-plugin-react
                "plugin:@typescript-eslint/recommended", // Uses the recommended rules from the @typescript-eslint/eslint-plugin
            ]
        }
    ],
    "rules": {
		// Place to specify ESLint rules. Can be used to overwrite rules specified from the extended configs
		// e.g. "@typescript-eslint/explicit-function-return-type": "off",
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "curly": "error",
        "no-var": "error",
        "eqeqeq": "error"
	},
```

**Comment by agorer** [comment]
Ok, so using the same extend in both overrides seems to do the trick 🤷 . It is a little bit strange but thanks for the solution @vgpechenkin ! 👍

**Comment by ccadieux** [comment]
@vgpechenkin Thanks for your example fixed my issue as well.
