### ISSUE TITLE
There are some conflicting eslint rules that is not ignored yet

### ISSUE THREAD

**Issue by trongthanh** [sveltejs/eslint-plugin-svelte3#12]
Here are a few eslint rules that conflict with Svelte 3 component special syntax (my config is based on Airbnb with exception of tabs as intent character):

```js
// the import/* rules is from eslint-plugin-import
{
    'import/first': 'off',               // import order cannot be determined correctly in .svelte components
    'import/no-mutable-exports': 'off',  // to dismiss `export let prop = 'default'` warning
    'no-labels': 'off',
    'no-restricted-syntax': ['error', 'ForInStatement', 'ForOfStatement', 'WithStatement'], // remove LabeledStatement from the list
}
```

I think we need a Svelte recommended eslint config to ease the integration of eslint into Svelte projects.

**Comment by Conduitry** [comment]
I think the label stuff makes sense to work around - and I'll take another sweep through the official ESLint rules to see if there are any others that should be disabled in Svelte components.

I'm wary about adding stuff from plugins though - that's a bit of a slippery slope - when do we stop? I'm currently leaning toward not doing anything special for them at all, and putting a warning in the readme saying that if you're using custom rules from plugins, you made need to use overrides to turn them off for Svelte components.

**Comment by trongthanh** [comment]
I agree we should avoid extra dependencies and just limit to the official ESLint rules. 

On the other hand, can we keep a document of other plugins' rules that conflict with Svelte syntax to save time for others.Probably a wiki here so that anyone can contribute to?

**Comment by MaxMilton** [comment]
There's been some discussion about examples for common Svelte usage scenarios over at https://github.com/sveltejs/svelte/issues/2656 . If we ever added an example for this plugin, it might be good to include info about conflicting rules there too.

**Comment by Conduitry** [comment]
Basic handling for `no-labels` and `no-restricted-syntax` rules has been added in v1.2.0 - I'm not sure yet what I want to do about documenting other gotchas.

**Comment by trongthanh** [comment]
Can I suggest that we expand this plugin to sub-config for popular plugins like `import`. Let's take `[eslint-config-prettier](https://github.com/prettier/eslint-config-prettier)` for example. They have opt-in subconfig for various frameworks like React, Vue...

**Comment by Conduitry** [comment]
I've added a new `OTHER_PLUGINS.md` describing some known issues with other plugins, partly based on your findings here. Thanks!
