### ISSUE TITLE
we should probably drop node 10 and add node 16

### ISSUE THREAD

**Issue by oscard0m** [sveltejs/eslint-plugin-svelte3#129]
we should probably drop node 10 and add node 16

_Originally posted by @benmccann in https://github.com/sveltejs/eslint-plugin-svelte3/pull/120#discussion_r703784615_

**Comment by Conduitry** [comment]
Is there a reason to drop this (besides this version of Node being EOL)? This would be a breaking change, which I would like to avoid if possible.

**Comment by benmccann** [comment]
I was only suggesting it because it's EOL, but no pressing reason to drop it

**Comment by oscard0m** [comment]
Should we keep version `10` but add version `16` to the matrix then? :)

**Comment by benmccann** [comment]
Sounds reasonable to me

**Comment by oscard0m** [comment]
> Sounds reasonable to me

Done
