### ISSUE TITLE
Integration with zodern:melte Meteor Svelte package

### ISSUE THREAD

**Issue by davidsavoie1** [sveltejs/eslint-plugin-svelte3#132]
I was wondering if there is any way to add a specific linting rule. I'm using Svelte as the front-end layer with [Meteor full-stack framework](https://www.meteor.com/) and one of the recommended packages is [zodern:melte](https://github.com/zodern/melte), which introduces a special Meteor-specific reactivity statement `$m:`.

Right now, I get a `'$m:' is defined but never used. no-unused-labels error`. I know I could silence this type of error entirely as a Svelte rule override, but I am wondering if there's a way to disable only this specific one, just as it is done for `$:` labels. [I already asked the maintainer](https://github.com/zodern/melte/issues/13) of this library about that, but I got referred here...

Thanks in adavance!

**Comment by Conduitry** [comment]
I don't think I want to add special handling for unofficial extensions to Svelte. Meteor/Zodern/whoever can create their own fork of this plugin if they choose.
