### ISSUE TITLE
$$Slots/$$Events type produces no-unused-vars error

### ISSUE THREAD

**Issue by wallw-bits** [sveltejs/eslint-plugin-svelte3#136]
The [commit here](https://github.com/sveltejs/eslint-plugin-svelte3/commit/e9f02506986b16480f04765f751057f65500d524) fixed a similar issue for `$$Generic`. In this case, I would like to type slot props and events [per the rfc here](https://github.com/dummdidumm/rfcs/blob/ts-typedefs-within-svelte-components/text/ts-typing-props-slots-events.md)

Example:
```svelte
<script lang="ts">
  import type ListItem from './ListItem';
  type T = $$Generic;

  interface $$Slots {
    default: {item: ListItem<T>};
  }
  // ...
</script>
<!-- ... -->
<slot {item}/>
```

However, that results in a `'$$Slots' is defined but never used  no-unused-vars` error. As a workaround I can use `eslint-disable` on that block.

**Comment by EirikFA** [comment]
Just adding that this goes for `$$Props` as well.
