### ISSUE TITLE
Cannot disable rule svelte(dynamic-slot-name)

### ISSUE THREAD

**Issue by ianhogersltn** [sveltejs/eslint-plugin-svelte3#145]
Hi,

I'm trying to use slot names via `ENUM` to make sure I don't have typo's in the slot names.

```
<script context="module" lang="ts">
	export const TESTING_SLOT_NAME = 'testing';
</script>

<slot name={TESTING_SLOT_NAME}></slot>
```

But i'm getting the error:
`<slot> name cannot be dynamicsvelte(dynamic-slot-name)`

I tried making the variable in typescript `ReadOnly<string>`

I also tried disabling the rule but it wouldn't work either.

Unless there's another way to safely type the slot names other than an `ENUM`?

**Comment by dummdidumm** [comment]
This is a Svelte compiler error, not a warning. This is an open feature request on the Svelte core repo: https://github.com/sveltejs/svelte/issues/6493
