### ISSUE TITLE
CSS custom properties handled as errors

### ISSUE THREAD

**Issue by nosovk** [sveltejs/eslint-plugin-svelte3#153]
CSS custom properties introduced in https://github.com/sveltejs/rfcs/pull/13 currently broke eslint cheking.

  <input --width="{numLength * 0.875 + 3}rem">

Will fire: '--width' is not a valid attribute name  ValidationError'

**Comment by dummdidumm** [comment]
Custom properties only work on components, not elements, so this is kind of expected.

**Comment by Conduitry** [comment]
Yeah, this isn't a valid Svelte component. That's an error from the compiler that you can also see if you paste that into the REPL.
