### ISSUE TITLE
eslint doesn't work

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [sveltejs/eslint-plugin-svelte3#171]
Eslint doesn't work at all, even when creating a new sveltekit app (skeleton or not).
I'm using VS Code with `pnpm` on linux.
EDIT: I just tried with `npm` and it also doesn't work.
EDIT2: I switched from vscode to vscodium (basically a reinstall) and I still have the problem.

The closest I got to make it work was by associating `.svelte` with `.html` files in my vscode settings, eslint did work but it considered the file as an html file, invalidating a lot of the svelte syntax.

`prettier-plugin-svelte` also didn't work for me to add prettier formatting but I did find a workaround by adding this in my vscode settings :
```json
	"[svelte]": {
		"editor.defaultFormatter": "svelte.svelte-vscode"
```

I don't have eslint errors but I do get TS typing errors (like `Type 'number' is not assignable to type 'string'`).

Steps to reproduce on my machine:

1. pnpm create svelte@next kit
> Skeleton project
> Use TypeScript ? Yes
> Add ESLint for code linting ? Yes
> Add Prettier for code formatting ? Yes
2. cd kit
3. pnpm i
4. `src/routes/index.svelte` :
```svelte
<script lang="ts">
	let a = 0;
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```
5. no eslint errors even `a` is not used, semicolon doesn't matter removing it doesn't add an error.

<hr>

`settings.json` :
```json
	"npm.packageManager": "pnpm",
	"eslint.packageManager": "pnpm",
	"eslint.probe": [
		"javascript",
		"javascriptreact",
		"typescript",
		"typescriptreact",
		"html",
		"vue",
		"markdown",
		"svelte"
	],
	"[svelte]": {
		"editor.defaultFormatter": "svelte.svelte-vscode"
	},
	"svelte.enable-ts-plugin": true,
	"svelte.plugin.html.tagComplete.enable": false,
	"svelte.plugin.html.renameTags.enable": false,
	"svelte.ask-to-enable-ts-plugin": false,
	"svelte.plugin.svelte.defaultScriptLanguage": "ts"
```

<hr>

`eslintrc.cjs` :
```js
module.exports = {
	root: true,
	parser: '@typescript-eslint/parser',
	extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'prettier'],
	plugins: ['svelte3', '@typescript-eslint'],
	ignorePatterns: ['*.cjs'],
	overrides: [{ files: ['*.svelte'], processor: 'svelte3/svelte3' }],
	settings: {
		'svelte3/typescript': () => require('typescript')
	},
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: 2020
	},
	env: {
		browser: true,
		es2017: true,
		node: true
	}
};
```

<hr>

`package.json` :
```json
{
  "name": "kit",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "package": "svelte-kit package",
    "preview": "svelte-kit preview",
    "check": "svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
    "lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
    "format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "@typescript-eslint/eslint-plugin": "^5.10.1",
    "@typescript-eslint/parser": "^5.10.1",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-svelte3": "^3.2.1",
    "prettier": "^2.5.1",
    "prettier-plugin-svelte": "^2.5.0",
    "svelte": "^3.44.0",
    "svelte-check": "^2.2.6",
    "svelte-preprocess": "^4.10.1",
    "tslib": "^2.3.1",
    "typescript": "~4.5.4"
  },
  "type": "module"
}
```

**Comment by Alexandre-Fernandez** [comment]
For some reason it works now after adding this to my `settings.json` : 
```json
"eslint.validate": ["javascript", "javascriptreact", "svelte"]
```

That's weird considering I already tried that before...

Anyway `eslint.validate` is considered an old legacy setting by the vscode extension :
> eslint.validate - an array of language identifiers specifying the files for which validation is to be enforced. This is an old legacy > setting and should in normal cases not be necessary anymore. Defaults to ["javascript", "javascriptreact"].

Is there a better way ?

**Comment by dummdidumm** [comment]
No, and this is also mentioned in the readme: https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/INTEGRATIONS.md#visual-studio-code

**Comment by pikeas** [comment]
Just ran into this. `eslint.validate` is a legacy setting that's been superceded by `eslint.probe`:

> eslint.probe = an array for language identifiers for which the ESLint extension should be activated and should try to validate the file. If validation fails for probed languages the extension says silent. Defaults to ["javascript", "javascriptreact", "typescript", "typescriptreact", "html", "vue", "markdown"].

> eslint.validate - an array of language identifiers specifying the files for which validation is to be enforced. This is an old legacy setting and should in normal cases not be necessary anymore. Defaults to ["javascript", "javascriptreact"].

VS Code ESLint will only run on Svelte files when `validate` is set, `probe` won't work. Is this something that can/should be updated in this plugin?

**Comment by EskelCz** [comment]
@dummdidumm Can we have this reopened? Still an issue.
