### ISSUE TITLE
Issue with global $$Props interface

### ISSUE THREAD

**Issue by ZerdoX-x** [sveltejs/eslint-plugin-svelte3#192]
Component below gives errors:
1) `An interface declaring no members is equivalent to its supertype  @typescript-eslint/no-empty-interface`
2) `error  'svelte' is not defined  no-undef`

```svelte
<script lang="ts">
  interface $$Props
    extends svelte.JSX.HTMLAttributes<HTMLElementTagNameMap["section"]> {}
</script>

<section class="section" {...$$restProps}>

</section>
```

**Comment by ptrxyz** [comment]
I assume those errors are eslint errors? To fix the 2nd point, simply add `globals: { svelte: true }` to your eslintrc.

**Comment by ZerdoX-x** [comment]
@ptrxyz Thank you!
