### ISSUE TITLE
Unexpected token : in transitions.

### ISSUE THREAD

**Issue by matyunya** [sveltejs/eslint-plugin-svelte3#24]
I have a few errors in my project all pointing to ":" character inside transitions.
`47:28  error  Parsing error: Unexpected token :`

`in:fly={{ y: 10, duration: 50 }}`
`in:fade={{ duration: 200, easing: quadIn }}`
`transition:fly="{{ y: -10, duration: 100, easing: quadOut }}"`

**Comment by Conduitry** [comment]
Thanks for the report! This should be fixed in 2.2.0.
