### ISSUE TITLE
imimport or impimport

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/eslint-plugin-svelte3#28]
Sometimes in a .svelte file with many imports using cli (or VSCode) it changes the first `import` in `imimport` or `impimport`.

**Comment by frederikhors** [comment]
I'm using this `.eslintrc.js`:

```js
module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: 'module'
  },
  env: {
    es6: true,
    browser: true,
    node: true
  },
  extends: [
    'eslint:recommended',
    'standard'
  ],
  plugins: ['svelte3'],
  overrides: [
    {
      files: '*.svelte',
      processor: 'svelte3/svelte3'
    }
  ]
}
```

**Comment by Conduitry** [comment]
I'll need a .svelte file that this happens with as well.

**Comment by frederikhors** [comment]
Yes, I now. I'm trying to create a reproducible gist.

**Comment by frederikhors** [comment]
Ok I have one example (different from mine, but something strange is happening here too).

From https://github.com/timhall/svelte-apollo:

```html
<script>
  import { getClient, query } from 'svelte-apollo';
  import { GET_BOOKS } from './queries';

  const client = getClient();

  const books = query(client, { query: GET_BOOKS });
</script>

{#await $books}
  Loading...
{:then result}
  {#each result.data.books as book}
    {book.title} by {book.author.name}
  {/each}
{:catch error}
  Error: {error}
{/await}
```

If you try with: `npx eslint --fix .\src\fileName.svelte` the error is:

`1:26  error  Unexpected token  ParseError`

**Comment by Conduitry** [comment]
Have you read https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/OTHER_PLUGINS.md#eslint-plugin-import ?

**Comment by frederikhors** [comment]
Ok. I'm using just `eslint-plugin-import`.

> If you're using them on other linted files, consider adding overrides for them for Svelte components.

How to do this?

**Comment by Conduitry** [comment]
https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files

**Comment by frederikhors** [comment]
It works. Thanks!
