### ISSUE TITLE
Using eslint --fix damage svelte file when using import and $: statement

### ISSUE THREAD

**Issue by robindanzinger** [sveltejs/eslint-plugin-svelte3#39]
### Environment
eslint@6.1.0
eslint-plugin-svelte@2.7.3
node@12.8.0
svelte@3.7.0

### Steps
1. Given Example.svelte File:
```
<script>
  import any from 'anywhere'

  const foo = true
  $: bar = 'foo is ' + foo
</script>
```

2. run in command line: eslint --fix Example.svelte

### Expected
nothing changed, everything fine.

### Actual

Commandline:
```
  1:13  error  Unexpected token  ParseError

✖ 1 problem (1 error, 0 warnings)

```

Example.svelte
```
<script>any from 'anywhere'

let bar;

  const foo = true
  $: bar = 'foo is ' + foo
</script>
```

**Comment by Conduitry** [comment]
What does your ESLint configuration look like?

This sounds like it would be caused by certain `eslint-plugin-import` rules, which, as explained [here](https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/OTHER_PLUGINS.md#eslint-plugin-import), are known not to work and need to be disabled in Svelte components.

**Comment by robindanzinger** [comment]
```
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true,
    "mocha": true
  },
  "extends": [
    "standard"
  ],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly"
  },
  "parserOptions": {
    "ecmaVersion": 2019,
    "sourceType": "module"
  },
  "rules": {
    "quotes": ["error", "single"]
  },
  "plugins": [
    "svelte3"
    ],
    "overrides": [
      {
        "files": ["**/*.svelte"],
        "processor": "svelte3/svelte3"
      }
    ]
}

```

**Comment by Conduitry** [comment]
You're extending from `standard`, which uses `eslint-plugin-import` internally. You need to disable the rules I linked to above.

**Comment by robindanzinger** [comment]
ok, thank you.
