### ISSUE TITLE
Enforcing keyed each blocks

### ISSUE THREAD

**Issue by dyslexicon** [sveltejs/eslint-plugin-svelte3#42]
Is there a way to configure this plugin to do that? If not, I kindly request it.

**Comment by Conduitry** [comment]
This is, up until now, really outside of the sorts of things this plugin does. So far, all of its errors and warnings either come directly from the Svelte compiler or directly from ESLint. It doesn't introduce any additional 'best practices' types of things about the component. Beyond that, there's the danger of getting into extreme niche territory. I'm not sure how I feel about this being added as a rule, or about this being something one would enforce on their components.

**Comment by pngwn** [comment]
Keyed each-blocks are a useful feature but they are only sometimes required and using them generates more code that the user will have to pay for.

I don't think we would ever consider this a 'best practice', probably the opposite, so a rule of this nature will not be forthcoming from an official plugin.

**Comment by dyslexicon** [comment]
>It doesn't introduce any additional 'best practices' ...

>I don't think we would ever consider this a 'best practice' ...

That's interesting, this does not seem to be the opinion of Vue where [require-v-for-key](https://eslint.vuejs.org/rules/require-v-for-key.html) is _strongly recommended_ and configured in eslint-plugin-vue by default. From the [style guide](https://vuejs.org/v2/style-guide/#Keyed-v-for-essential):

>### Always use key with v-for.
>
>`key` with `v-for` is always required on components, in order to maintain internal component >state down the subtree. Even for elements though, it’s a **good practice** to maintain predictable >behavior, such as [object constancy](https://bost.ocks.org/mike/constancy/) in animations.

Maybe there's implementation differences between Svelte & Vue? Seemed like a good practice to me—one less thing that's easy to forget about and can cause bugs. But what do I know? ¯\\\_(ツ)\_/¯

**Comment by pngwn** [comment]
Vue doesn't generate different code depending on whether you use `keys` or not, so the cost of using a key is smaller there but the implementation may also differ. There are definitely times you should use keys but I don't think a strict rule is necessary, if we wanted people to always key list items then we would add a compiler warning.

**Comment by dyslexicon** [comment]
I wasn't looking for a strict rule

> we would add a compiler warning

I'd agree that's _too_ opinionated. I was looking for a way to add a configuration (for my personal preference) to my eslint config—not even suggesting it be configured by default. But I'll find a work around in the meantime (or indefinitely).🙂
