### ISSUE TITLE
Is there any way to lint the HTML within Svelte components?

### ISSUE THREAD

**Issue by radarsh** [sveltejs/eslint-plugin-svelte3#44]
Is there any way to lint the HTML within Svelte components?

**Comment by Conduitry** [comment]
It is not, beyond the warnings alread emitted by the Svelte compiler itself.

This plugin reports only errors that come from the compiler or from ESLint. I'm not at all sure what linting the HTML would entail. That sounds really open-ended.

**Comment by arjunkalburgi** [comment]
Any progress made here? Has it been explored at all? I would really like to make some custom lint rules for the HTML in my Svelte files.
