### ISSUE TITLE
WebStorm / IntelliJ support?

### ISSUE THREAD

**Issue by shirotech** [sveltejs/eslint-plugin-svelte3#45]
Hi there,

I'm trying to get eslint error highlighting to work with WebStorm, having great difficulty, was wondering if it's a configuration issue or it doesn't support this at the moment. If any WebStorm users out there could get it working, would be awesome if you can share. Thanks.

Things I've tried:

- Using this plugin https://plugins.jetbrains.com/plugin/12375-svelte however, it doesn't support embedding eslint yet and pending https://github.com/tomblachut/svelte-intellij/issues/24
- Set the filetype to `html`, and adding `eslint-plugin-html`, which means I can get syntax highlighting, I can get eslint errors to highlight, but no svelte syntax.
- I did the above and in addition to adding `eslint-plugin-svelte3`, The ide just won't highlight eslint errors anymore since it is incompatible with `eslint-plugin-html`.

Any other options?

Edit: All those WebStorm / IntelliJ users out there, please upvote https://youtrack.jetbrains.com/issue/WEB-27366 for them to consider officially supporting Svelte.

**Comment by jvanderen1** [comment]
I would like to know as well. After following the [tweened](https://svelte.dev/docs/#tweened) example from the docs, I receive this error message from IntelliJ:

<img width="703" alt="Screen Shot 2019-12-07 at 4 25 02 PM" src="https://user-images.githubusercontent.com/22926257/70380773-2c330880-190e-11ea-9748-6acfd48c466d.png">

And from `prettier`:

```
> eslint src/** --ext .svelte

  22:24  error  Replace `⏎);(` with `;`  prettier/prettier
  23:33  error  Insert `;`               prettier/prettier

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

Any suggestions?

**Comment by Conduitry** [comment]
Working nicely with Prettier has its own issue, #16. If that's your only problem, I'd say you've gotten this working as well as you could expect currently.

**Comment by jvanderen1** [comment]
Good to know. However, there's still an issue with IntelliJ

**Comment by dummdidumm** [comment]
This might have been implemented by the Svelte IntelliJ-Plugin according to [this issue](https://github.com/tomblachut/svelte-intellij/issues/24).
