### ISSUE TITLE
Unwanted semicolons are added

### ISSUE THREAD

**Issue by lud** [sveltejs/eslint-plugin-svelte3#52]
Hi, 

The plugin seem to work fine for me, except from the command line where it chokes on html tags (unexpected '<').

Although, i have this rule to discard all semicolons:

```
    'semi': [ 'error', 'never' ],
```

and it works fine for .js files, but has the opposite effect on .svelte files: semicolons are added if not present.

Is it expected behaviour or a bug ?

**Comment by TehShrike** [comment]
I'm currently using `eslint-plugin-svelte3` with `"semi": ["warn", "never"] and semicolons are removed from `.svelte` files when I run eslint with `--fix`

**Comment by Conduitry** [comment]
It sounds like it would be a bug, but it's not one I can reproduce either. Do you have a small repo that can be cloned and demonstrate this?

**Comment by Conduitry** [comment]
👍 See #50 for discussion on how we can make it clearer in the docs what you need to do to set up things in vscode.
