### ISSUE TITLE
[Bug] Can not use with typescript

### ISSUE THREAD

**Issue by ksewo** [sveltejs/eslint-plugin-svelte3#53]
I have described this issue in svelte repository issues:
https://github.com/sveltejs/svelte/issues/4357

**Comment by Conduitry** [comment]
This isn't a bug report, it's a huge feature request, and not one we're going to be spending any time on before we decide what official TypeScript support in Svelte is going to look like. Right now there are a number of competing third-party solutions, and 'making the eslint plugin work with typescript' is not a well defined goal.

**Comment by rondonjon** [comment]
Hello @Conduitry, I've been reading about the different approaches on Typescript in Svelte; it seems that this is now mainly about a preprocessor vs. language tools decision; in the end I wonder if if would matter this much to an eslint plugin as their approaches on source code level don't seem to differ that much; they both assume a hint (`lang="typescript` or `type="typescript"`) on the `<script>` and pass the content to the Typescript compiler. The differences are rather in how these tools are invoked and how they interact with an IDE. So I was wondering if, in the meanwhile, it might be possible to do the same (check attribute and eventually pass content to TS compiler) in the eslint plugin?

**Comment by Zimtir** [comment]
Now Svelte supports TypeScript, but we need not provide a lang="typescript" because can configure svelte.config with typescript by default
