### ISSUE TITLE
Something corupts file when running with `--fix`

### ISSUE THREAD

**Issue by mirth** [sveltejs/eslint-plugin-svelte3#54]
<img width="333" alt="Screenshot 2020-02-13 at 14 30 56" src="https://user-images.githubusercontent.com/1296970/74432923-77b6e500-4e70-11ea-9c73-a5da6b2b0b81.png">
<img width="289" alt="Screenshot 2020-02-13 at 14 30 44" src="https://user-images.githubusercontent.com/1296970/74432925-7980a880-4e70-11ea-9957-76306854bbea.png">

It seems it's trying to fix `error    Import in body of module; reorder to top      import/first` this way.

Versions:
```
├─ eslint-config-airbnb-base@14.0.0
├─ eslint-import-resolver-node@0.3.2
├─ eslint-module-utils@2.5.0
├─ eslint-plugin-import@2.18.2
│  ├─ eslint-import-resolver-node@^0.3.2
│  ├─ eslint-module-utils@^2.4.0
├─ eslint-plugin-svelte3@2.7.3
├─ eslint-scope@5.0.0
├─ eslint-utils@1.4.3
│  └─ eslint-visitor-keys@^1.1.0
├─ eslint-visitor-keys@1.1.0
├─ eslint@6.7.2
│  ├─ eslint-scope@^5.0.0
│  ├─ eslint-utils@^1.4.3
│  ├─ eslint-visitor-keys@^1.1.0
│  └─ eslint-visitor-keys@^1.1.0
```

.eslintrc
```
{
  "parserOptions": {
    "ecmaVersion": 2019,
    "sourceType": "module"
  },
  "extends": "airbnb-base",
  "env": {
    "es6": true,
    "browser": true
  },
  "plugins": [
    "svelte3"
  ],
  "overrides": [
    {
      "files": ["**/*.svelte"],
      "processor": "svelte3/svelte3"
    }
  ],
  "rules": {
    "import/no-extraneous-dependencies": ["error", {"devDependencies": true}],

    // so that svelte export const to be worked
    "import/no-mutable-exports": "off",
    "import/prefer-default-export": "off"
  }
}
```

**Comment by PKlknr** [comment]
Have you tried disabling `import/first`? Seems to be enabled in `airbnb-base`.

(`imports/first` is considered problematic according to [Interactions with other plugins](https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/OTHER_PLUGINS.md))

**Comment by mirth** [comment]
Yep, it's the workaround for now.
Should i close the issue then?

**Comment by Conduitry** [comment]
Yep, because of the way this plugin works, there's not really a reasonable way to get along with `import/first`. Closing.
