### ISSUE TITLE
How svelte3/ignore-styles ?

### ISSUE THREAD

**Issue by drop1down** [sveltejs/eslint-plugin-svelte3#55]
Please help.
I have no idea how to add "svelte3/ignore-styles" to settings in .eslintrc.js file
I need a function?

this do not work:
settings: {"svelte3/ignore-styles": true}

i need to disable all styles - i use svelte-preprocess with stylus

**Comment by Conduitry** [comment]
Yes as described [here](https://github.com/sveltejs/eslint-plugin-svelte3#svelte3ignore-styles) this needs to be a function that returns true or false. See also #43.

**Comment by tal1992** [comment]
Change .eslintrc to .eslintrc.js and wrap the json inside module.exports, then you can use the rule as below -

`module.exports = {
    ...
    
    "rules" : {

    },

    "settings": {
      "svelte3/ignore-styles": () => true
    }

}`
