### ISSUE TITLE
using in VS Code without the Svelte extension

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/eslint-plugin-svelte3#56]
I am trying to get ESLint to run on `.svelte` files in VS Code without installing the Svelte extension.
Here is what I have tried so far.

```bash
npx degit sveltejs/template demo
cd demo
npm install -D eslint eslint-plugin-svelte3
npm install -D prettier@1.19.1 prettier-plugin-svelte
```

Edit `package.json` and add these to `scripts`:

```json
    "format": "prettier --write '{public,src}/**/*.{css,html,js,svelte}'",
    "lint": "eslint --fix --quiet src --ext .js,.svelte",
```
Create `.eslintrc.json` containing this:

```json
{
  "env": {
    "browser": true,
    "es6": true
  },
  "extends": ["eslint:recommended"],
  "overrides": [
    {
      "files": ["**/*.svelte"],
      "processor": "svelte3/svelte3"
    }
  ],
  "parserOptions": {
    "sourcetype": "module"
  },
  "plugins": ["svelte3"]
}
```

Create `.prettierrc` containining this:

```json
{
  "bracketSpacing": false,
  "singleQuote": true,
  "svelteSortOrder": "scripts-markup-styles"
}
```

Entering `npm run lint` from a terminal works and correctly identifies JavaScript errors in `.svelte` files.
Entering `npm run format` from a terminal works.
Opening a `.svelte` file in VS Code that has JavaScript errors does not underline the errors.
I must be missing some configuration.

**Comment by Conduitry** [comment]
Did you read [the document about editor integrations linked to in the readme](https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/INTEGRATIONS.md)?

**Comment by mvolkmann** [comment]
Yes, I got confused by this found at https://github.com/microsoft/vscode-eslint/blob/master/README.md:

**eslint.probe** = an array for language identifiers for which the ESLint extension should be activated and should try to validate the file. If validation fails for probed languages the extension says silent. Defaults to ["javascript", "javascriptreact", "typescript", "typescriptreact", "html", "vue"].

**eslint.validate** - an array of language identifiers specifying the files for which validation is to be enforced. **This is an old legacy setting and should in normal cases not be necessary anymore.** Defaults to ["javascript", "javascriptreact"].

When I add the following as you suggest then it works:

```json
{
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "html"
  ]
}
```

Thanks!
