### ISSUE TITLE
Prevent local Dev compile when there is a linting error

### ISSUE THREAD

**Issue by freeman-g** [sveltejs/eslint-plugin-svelte3#63]
Thanks for the great plugin. I'm used to the vue-cli configuration which prevents local dev compilation when there is a linting error.

Is it possible to configure this plugin with ESLint + Rollup to prevent local Svelte dev compilation?

Ideally any linting errors would show up in the console output where I ran `npm run dev`.

In my case I initialized a standard Svelte project with `npx degit sveltejs/template my-svelte-project`

This would help me catch errors as I'm developing vs having to run eslint externally or during another step.

**Comment by Conduitry** [comment]
The `eslint` CLI returns a non-zero error code when there are linting errors, so you can just have the ESLint call run before your build with `&&`. This all works how it normally does in ESLint - this plugin doesn't play a part in this.

**Comment by freeman-g** [comment]
@Conduitry I am doing that. Here's my current setup:

```
  "scripts": {
    "build": "npx eslint ./src && rollup -c",
    "dev": "npx eslint ./src && rollup -c -w",
    "start": "sirv public"
  },
```

But this only works a single time when I run a build or start the dev environment.

What I'm looking for is 'real-time' linting errors during a hot-load event.

So for example, I run npm run dev and I have local dev running. As I'm developing, I introduce an error, I would like for the hot-loading dev environment to run ESLint and show me the errors then vs. only later when I run a production build.

The vue-cli works in the hot loading way I'm describing and it helps catch errors faster.

Thanks!

**Comment by Conduitry** [comment]
If you want to lint everything as it's getting bundled - including during rebuilds in dev/watch mode - you could try a Rollup plugin that runs ESLint as part of bundling. But all of this is outside the scope of this plugin.
