### ISSUE TITLE
`Error: Cannot find module 'eslint-config-plugin/svelte3'`

### ISSUE THREAD

**Issue by foogunlana** [sveltejs/eslint-plugin-svelte3#7]
I tried to run `eslint` after installing everything.
```
npm i --save-dev eslint eslint-plugin-svelte3
```
But I get this error:
```
 Cannot find module 'eslint-config-plugin/svelte3'
```
Here is what my eslintrc looks like:
```
module.exports = {
  env: {
    browser: true,
    es6: true
  },
  extends: ['eslint:recommended', 'prettier', 'plugin/svelte3'],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly'
  },
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module'
  },
  rules: {
    indent: ['error', 4],
    'linebreak-style': ['error', 'unix'],
    quotes: ['error', 'single'],
    semi: ['error', 'never']
  }
};
```

**Comment by Conduitry** [comment]
Use need to have `plugins: ['svelte3']` to use the plugin, not put it in the `extends` array.

The readme says "Just add svelte3 to the array of plugins in your .eslintrc.*." but maybe this could be clearer? Not sure.

**Comment by foogunlana** [comment]
Sorry about that. Rookie error. I hastily misread the readme. Thanks for the quick response! It works fine now with another error Cannot find svelte/compiler. I'm pretty sure I've installed svelte, eslint and the plugin, but I will do some digging before deciding there's any actual problem.

**Comment by foogunlana** [comment]
You can close this by the way, I needed to update to svelte3 and it works fine!
