### ISSUE TITLE
ESlint is processing scss inside style tags

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/eslint-plugin-svelte3#70]
My NPM command
```
eslint src/** --ext .js,.svelte
```
My .eslintrc.js
```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: "module",
  },
  env: {
    es6: true,
    browser: true,
  },
  plugins: ["svelte3"],
  overrides: [
    {
      files: ["*.svelte"],
      processor: "svelte3/svelte3",
    },
  ]
};
```
Output:
![image](https://user-images.githubusercontent.com/24741538/89323776-e4829d80-d6a3-11ea-831a-bac7c512ea20.png)
![image](https://user-images.githubusercontent.com/24741538/89324010-362b2800-d6a4-11ea-9a45-91fa705ec990.png)

OS: Windows
My ESlint version: 7.6.0
eslint-plugin-svelte3: 2.7.3

**Comment by Conduitry** [comment]
See https://github.com/sveltejs/eslint-plugin-svelte3#svelte3ignore-styles

**Comment by TheComputerM** [comment]
No, this error is still happening when I set svelte3/ignore-styles to 0
```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: "module",
  },
  env: {
    es6: true,
    browser: true,
  },
  plugins: ["svelte3"],
  overrides: [
    {
      files: ["**/*.svelte"],
      processor: "svelte3/svelte3",
    },
  ],
  rules: {
    "svelte3/ignore-styles": 0
  }
};
```

**Comment by pngwn** [comment]
> This setting can be given a function that accepts an object of attributes on a <style> tag (like that passed to a Svelte preprocessor) and returns whether to ignore the style block for the purposes of linting.

**Comment by TheComputerM** [comment]
```js
...
settings: {
  "svelte3/ignore-styles": true
}
...
```

![image](https://user-images.githubusercontent.com/24741538/89326187-89eb4080-d6a7-11ea-8f48-e61bddd44d0b.png)

**Comment by pngwn** [comment]
> This setting can be given a function

**Comment by TheComputerM** [comment]
What should be the function then?

**Comment by pngwn** [comment]
```
settings: {
  "svelte3/ignore-styles": true
}
```

This is not a function. Give it a function.

**Comment by TheComputerM** [comment]
Yeah thanks, `() => true` seems to work
