### ISSUE TITLE
Import in body of module; reorder to top

### ISSUE THREAD

**Issue by december1981** [sveltejs/eslint-plugin-svelte3#73]
I've had to disable this rule ("import/first") for the svelte plugin. Even though I've added imports at the top of the <script> section of a .svelte file, it still complains. (Although strangely, it doesn't complain for every svelte file in my project that imports in its script tags).

Am I doing something wrong perhaps?

**Comment by Conduitry** [comment]
See https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/OTHER_PLUGINS.md#eslint-plugin-import

**Comment by december1981** [comment]
Sorry, my mistake.
