### ISSUE TITLE
Problem with sorting imports, removing unnecessary "{" and changing "let" to "const"

### ISSUE THREAD

**Issue by crosspath** [sveltejs/eslint-plugin-svelte3#75]
Enabled ESLint rules for `*.svelte` files:

1. `prefer-const: error`
2. `curly: [error, multi, consistent]`
3. `simple-import-sort/sort: error` ([this plugin](https://github.com/lydell/eslint-plugin-simple-import-sort))

I got these problems with autofix:

1. Removed indents for `import` statements (except first).
2. Broken file path in last `import` (see below: file path changed from `components/forms/text-node` to `components/forms/text-nodeos`).
3. Broken multiline `let` statements (see below: line changed from `let type = event.type,` to `leconstype = event.type,`).
4. Removed unnecessary "{" as expected, but kept "}".

Also ESLint prints this error message (it points to `else`):
```
13:8  error  Unexpected token  ParseError
```

Transforms this file:
```svelte
<script>
  import TextNode from 'components/forms/text-node';
  import axios from 'axios';
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  function handle_event(event) {
    let type = event.type,
        node = event.currentTarget;
    if (type == 'click') {
      dispatch('click');
    } else {
      dispatch('other', event.type);
    }
  }
</script>
```

Into this:
```svelte
<script>
  import axios from 'axios';
import TextNode from 'components/forms/text-nodeos';
  import {createEventDispatcher} from 'svelte';

  const dispatch = createEventDispatcher();

  function handle_event(event) {
    leconstype = event.type,
        node = event.currentTarget;
    if (type == 'click') 
    dispatch('click');
     } else 
    dispatch('other', event.type);
     }
  }
</script>
```

Difference:
```svelte
-  import TextNode from 'components/forms/text-node';
   import axios from 'axios';
-  import { createEventDispatcher } from 'svelte';
+import TextNode from 'components/forms/text-nodeos';
+  import {createEventDispatcher} from 'svelte';
 
   const dispatch = createEventDispatcher();
 
   function handle_event(event) {
-    let type = event.type,
+    leconstype = event.type,
         node = event.currentTarget;
-    if (type == 'click') {
+    if (type == 'click') 
       dispatch('click');
-    } else {
+     } else 
       dispatch('other', event.type);
     }
   }
```

**Comment by Conduitry** [comment]
`eslint-plugin-import` is known not to interact well with this plugin - see https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/OTHER_PLUGINS.md. I realize this isn't the plugin this issue is referring to, but I would imagine it's the result of them both converting a `.svelte` file (which may contain multiple `<script>` blocks) to a single `.js` file before passing it along to ESLint. I'm open to PRs that would address this (although I'm not at all sure how they would work), and I don't really have a feel for how mainstream that plugin is or whether it's something that should be listed in the above documentation. The readme does essentially say that you need to be on the alert for bad interactions whenever you're using other plugins, but I did try to list some of the more common plugins that have issues. For now this isn't something I'm likely to be spending time on.

**Comment by crosspath** [comment]
That's sad, but ok. What about curly braces and changing "let" to "const"? Is it fixable?

**Comment by mattfysh** [comment]
Running into this issue also, but it's not related to import. I turned off the `no-else-return` rule and no longer had `--fix` generate invalid syntax. I'm not sure what the solution is, but it seems to be that the rewriting code is not working well with Svelte components. I'll try to find a way to disable autofixing code for Svelte files

**Comment by pikeas** [comment]
I'm being bit by this as well. Here's a simple repro:

```
<script>
    import b from "b"
    import a from "a"
</script>

<div>Test</div>
```

Output:

```
<script>
    import b fra from "a"
import b from "b"
</script>
```

Note that "from" becomes "fra from", which is invalid syntax.

Relevant config:

```
        "import/order": [
            "error",
            {
                alphabetize: {
                    order: "asc",
                },
            },
        ],

```

Related: #72

**Comment by ritchieanesco** [comment]
> `eslint-plugin-import` is known not to interact well with this plugin - see https://github.com/sveltejs/eslint-plugin-svelte3/blob/master/OTHER_PLUGINS.md. I realize this isn't the plugin this issue is referring to, but I would imagine it's the result of them both converting a `.svelte` file (which may contain multiple `<script>` blocks) to a single `.js` file before passing it along to ESLint. I'm open to PRs that would address this (although I'm not at all sure how they would work), and I don't really have a feel for how mainstream that plugin is or whether it's something that should be listed in the above documentation. The readme does essentially say that you need to be on the alert for bad interactions whenever you're using other plugins, but I did try to list some of the more common plugins that have issues. For now this isn't something I'm likely to be spending time on.

@Conduitry is there an alternative that you can recommend?

**Comment by pikeas** [comment]
Just tried eslint-plugin-simple-import-sort, same issue.

Before:

```
<script>
    import {dev} from "$app/env" // eslint-disable-line import/no-unresolved
    import CookieConsent from "$lib/layout/CookieConsent.svelte"
    import Footer from "$lib/layout/Footer.svelte"
    import Nav from "$lib/layout/Nav.svelte"

    import "../app.css"
</script>
```

After:

```
<script>
    import "../app.css"

import {dev} from "$app/env" // eslint-disable-line import/no-unresolved
import CookieConsent from "$lib/layout/CookieConsent.svelte"
import Footer from "$lib/layout/Footer.svelte"
import Nav from "$lib/layout/Nav.svelteport "../app.css"
</script>
```

@Conduitry What sorts of transforms is your plugin applying that might cause downstream plugins to cross line boundaries when applying fixes? 

>  I would imagine it's the result of them both converting a .svelte file (which may contain multiple <script> blocks) to a single .js file before passing it along to ESLint.

Have you considered using [ESLint's preprocess](https://eslint.org/docs/developer-guide/working-with-plugins)? You could potentially parse one `.svelte` file into several virtual files: a) `component.js` (or ts), b) `component-module.js` (for context=module), c) `component.css` (for style tag), and apply your plugin's rules to the remainder?

**Comment by lydell** [comment]
I found the issue causing this: https://github.com/sveltejs/eslint-plugin-svelte3/issues/110

**Comment by dummdidumm** [comment]
Closing in favor of #110
