### ISSUE TITLE
Why not use `eslint-plugin-svelte` as pkg name directly?

### ISSUE THREAD

**Issue by JounQin** [sveltejs/eslint-plugin-svelte3#90]
I'm confused about the name of this plugin, [`eslint-plugin-svelte`](https://www.npmjs.com/package/eslint-plugin-svelte) is not taken on npm.

**Comment by Conduitry** [comment]
I don't want to have to support multiple major versions of Svelte with a single version of this plugin, and I want it to be very clear which major version of Svelte a particular version of the plugin is for, and I want to be able to have breaking changes (major version bumps) in this plugin while still within a single major version of Svelte.
