### ISSUE TITLE
TypeScript support not available with deterministic configuration

### ISSUE THREAD

**Issue by jnordberg** [sveltejs/eslint-plugin-svelte3#95]
I use a `.eslintrc` JSON config and are unable to pass the `"svelte3/typescript": require('typescript')` setting. Would be great to be able to turn on TypeScript support, I suggest that passing a value of `true` there would do a `require('typescript')` for you.

**Comment by dummdidumm** [comment]
Since this came up in two different instances now, what do you think @Conduitry , should we bite the bullet and allow that after all?

**Comment by CherryDT** [comment]
Deterministic config causes more issues than that, though, right? Like, you can't pass functions like `() => true` as value to settings either.

**Comment by Conduitry** [comment]
I dunno. I feel like the longer we go without this, the more it's something that I don't really want to add. ESLint has been encouraging people to use `.eslintrc.js` files for a while now.

**Comment by dummdidumm** [comment]
If eslint encourages it then I see no point in adding this right now.

**Comment by Conduitry** [comment]
I don't think I've ever seen a primary source for that, though, and I don't remember what my secondary source was. If a mention of this does exist somewhere and if it could be tracked down, I think this and #43 could be closed. I'm about to ask in the ESLint Discord whether I or someone else was making up that this is an official position of ESLint.

**Comment by Conduitry** [comment]
Apparently whoever I heard that from was making it up, because I just heard this back from nzakas:

> There is no preferred format for config files and we encourage plugin authors to make sure their plugins work regardless of the config file format people are using.

So, that's that then, I guess. It'd probably be stubborn of me to continue to block this and #43.

**Comment by Conduitry** [comment]
In 3.2.0, you can now use `"svelte3/typescript": true`, which will load the TS compiler, resolving from the location of the plugin.
